[server]
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50
headless = false

[browser]
gatherUsageStats = false
showErrorDetails = true
serverAddress = "localhost"

[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
caching = true
displayEnabled = true
toolbarMode = "auto"

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true
fastReruns = true

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[global]
developmentMode = false
logLevel = "info"
unitTest = false

[ui]
hideTopBar = false
hideSidebarNav = false